// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
if (process.env.NODE_ENV !== "production") {
  // @ts-ignore
  import("dotenv/config").catch(() => {});
}
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
