"use client";

import { useState } from "react";
import { format, isWithinInterval } from "date-fns";
import { CalendarDays, Download, Sparkles, Clock, AlertCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

type ScheduleBlock = {
  id: string;
  taskId: string | null;
  title: string;
  startTime: Date;
  endTime: Date;
  aiGenerated: boolean;
};

export function CalendarView({
  blocks: initialBlocks,
  autoScheduleAction,
}: {
  blocks: any[];
  autoScheduleAction: () => Promise<void>;
}) {
  const [blocks] = useState<ScheduleBlock[]>(
    initialBlocks.map((b) => ({
      ...b,
      startTime: new Date(b.startTime),
      endTime: new Date(b.endTime),
    })),
  );

  const today = new Date();
  const todayBlocks = blocks.filter(
    (b) => b.startTime.toDateString() === today.toDateString(),
  );

  // Hours to show in timeline (8:00 AM to 8:00 PM)
  const hours = Array.from({ length: 13 }, (_, i) => i + 8); // [8, 9, ..., 20]

  const formatHour = (h: number) => {
    const ampm = h >= 12 ? "PM" : "AM";
    const displayHour = h % 12 === 0 ? 12 : h % 12;
    return `${displayHour}:00 ${ampm}`;
  };

  const handleExportICS = () => {
    if (blocks.length === 0) return;

    let icsContent = "BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//Last-Minute Life Saver//EN\nCALSCALE:GREGORIAN\n";
    
    blocks.forEach((block) => {
      const startStr = block.startTime.toISOString().replace(/[-:]/g, "").split(".")[0] + "Z";
      const endStr = block.endTime.toISOString().replace(/[-:]/g, "").split(".")[0] + "Z";
      
      icsContent += "BEGIN:VEVENT\n";
      icsContent += `UID:${block.id}@lastminutelifesaver.com\n`;
      icsContent += `DTSTAMP:${startStr}\n`;
      icsContent += `DTSTART:${startStr}\n`;
      icsContent += `DTEND:${endStr}\n`;
      icsContent += `SUMMARY:${block.title.replace(/,/g, "\\,")}\n`;
      icsContent += "DESCRIPTION:AI-scheduled focus block generated by Last-Minute Life Saver.\\n\n";
      icsContent += "STATUS:CONFIRMED\n";
      icsContent += "SEQUENCE:0\n";
      icsContent += "END:VEVENT\n";
    });
    
    icsContent += "END:VCALENDAR";

    const blob = new Blob([icsContent], { type: "text/calendar;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `life-saver-schedule-${format(today, "yyyy-MM-dd")}.ics`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="space-y-6">
      <header className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Smart schedule</h1>
          <p className="mt-1 text-muted">
            AI-generated time blocks based on urgency, effort, and deadline safety boundaries.
          </p>
        </div>
        <div className="flex gap-2">
          <Button variant="secondary" onClick={handleExportICS} disabled={blocks.length === 0}>
            <Download className="h-4 w-4" />
            Export to Google Calendar (.ics)
          </Button>
          <form action={autoScheduleAction}>
            <Button type="submit">
              <Sparkles className="h-4 w-4" />
              Regenerate schedule
            </Button>
          </form>
        </div>
      </header>

      <div className="grid gap-6 lg:grid-cols-3">
        {/* Timeline Grid */}
        <Card className="lg:col-span-2 p-6">
          <CardHeader
            title={`Today's Agenda — ${format(today, "EEEE, MMM d")}`}
            subtitle={
              todayBlocks.length > 0
                ? `${todayBlocks.length} AI focus blocks planned`
                : "Your schedule is clear"
            }
          />

          {todayBlocks.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-12 text-center text-muted">
              <AlertCircle className="h-10 w-10 text-muted/60 mb-2" />
              <p className="text-sm">No scheduled blocks for today.</p>
              <p className="text-xs text-muted/80 mt-1">
                Click &quot;Regenerate schedule&quot; to auto-allocate time for your pending tasks.
              </p>
            </div>
          ) : (
            <div className="relative mt-6 border-l border-border pl-6 space-y-8">
              {hours.map((hour) => {
                // Find blocks falling in this hour (startTime hours match)
                const hourBlocks = todayBlocks.filter((b) => {
                  const startHour = b.startTime.getHours();
                  return startHour === hour;
                });

                return (
                  <div key={hour} className="relative group">
                    {/* Hour line bullet */}
                    <div className="absolute -left-[31px] top-1.5 h-3.5 w-3.5 rounded-full border border-background bg-border group-hover:bg-accent transition-colors" />
                    
                    <div className="flex flex-col sm:flex-row sm:items-start gap-4">
                      <span className="font-mono text-xs font-semibold text-muted w-24 pt-1 select-none">
                        {formatHour(hour)}
                      </span>

                      <div className="flex-1 space-y-2">
                        {hourBlocks.length > 0 ? (
                          hourBlocks.map((block) => {
                            const active = isWithinInterval(new Date(), {
                              start: block.startTime,
                              end: block.endTime,
                            });

                            return (
                              <div
                                key={block.id}
                                className={`rounded-xl border p-4 shadow-sm transition-all duration-300 ${
                                  active
                                    ? "border-accent bg-accent/10 shadow-md scale-[1.01]"
                                    : "border-border bg-surface hover:border-accent/40"
                                }`}
                              >
                                <div className="flex items-start justify-between gap-2">
                                  <div>
                                    <p className="font-semibold text-sm">{block.title}</p>
                                    <div className="mt-1 flex items-center gap-1 text-xs text-muted">
                                      <Clock className="h-3 w-3" />
                                      <span>
                                        {format(block.startTime, "h:mm a")} - {format(block.endTime, "h:mm a")}
                                      </span>
                                    </div>
                                  </div>
                                  <div className="flex flex-col items-end gap-1.5">
                                    {active && (
                                      <Badge variant="success" className="animate-pulse">
                                        Active Now
                                      </Badge>
                                    )}
                                    {block.aiGenerated && (
                                      <Badge variant="muted">AI Scheduled</Badge>
                                    )}
                                  </div>
                                </div>
                              </div>
                            );
                          })
                        ) : (
                          <div className="h-6 flex items-center">
                            <span className="text-xs text-muted/40 italic">Open slot</span>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </Card>

        {/* Sidebar Info/Overview */}
        <Card className="p-6">
          <CardHeader title="Calendar Integration" subtitle="Export options" />
          <div className="space-y-4 text-sm mt-4">
            <div className="rounded-xl border border-border p-4 bg-surface-muted/30">
              <p className="font-semibold text-xs text-foreground uppercase tracking-wider">How to import to Google Calendar</p>
              <ol className="list-decimal list-inside text-xs space-y-2 mt-2 text-muted">
                <li>Click the <b>Export to Google Calendar</b> button to save the <code>.ics</code> file.</li>
                <li>Open <b>Google Calendar</b> in your browser.</li>
                <li>Go to <b>Settings &gt; Import &amp; export</b>.</li>
                <li>Upload the downloaded file and select your calendar.</li>
              </ol>
            </div>
            
            <div className="rounded-xl border border-border p-4 bg-surface-muted/30">
              <p className="font-semibold text-xs text-foreground uppercase tracking-wider">AI Scheduling Logic</p>
              <p className="text-xs mt-2 leading-relaxed text-muted">
                The scheduler sorts all pending tasks by urgency score, factors in estimated durations, and assigns contiguous focus blocks starting from 9:00 AM, skipping overnight hours to ensure sustainable work pacing.
              </p>
            </div>
          </div>
        </Card>
      </div>
    </div>
  );
}
